### PR TITLE
fix(poller): Next height should not be set with a lower value

### LINKED ISSUE #234: Fast-sync inconsistent with poller

### PR DESCRIPTION
**Pull request by gitferry**
This PR potentially fixed #234. We need to ensure that after fast sync, the poller is still up-to-date. This PR ensures that the next height of the poller should not be set with a lower value.

### CODE REVIEW

File: finality-provider/service/chain_poller.go [hunk 1]
```diff
@@ -261,7 +261,9 @@ func (cp *ChainPoller) getNextHeight() uint64 {
 func (cp *ChainPoller) setNextHeight(height uint64) {
 	cp.mu.Lock()
 	defer cp.mu.Unlock()
-	cp.nextHeight = height
+	if cp.nextHeight < height {
```
Comment (vitsalis) [inline finality-provider/service/chain_poller.go:264]: Maybe the caller (e.g. `SetNextHeight`) does this check and we keep this as an internal setter?

Comment (gitferry) [reply finality-provider/service/chain_poller.go:268]: Good point. Done.

File: finality-provider/service/chain_poller.go [hunk 2]
```diff
@@ -249,23 +249,25 @@ func (cp *ChainPoller) pollChain() {
...
 	return cp.nextHeight
 }
 
 func (cp *ChainPoller) setNextHeight(height uint64) {
-	cp.mu.Lock()
-	defer cp.mu.Unlock()
 	cp.nextHeight = height
 }
 
 func (cp *ChainPoller) SetNextHeight(height uint64) {
```
Comment (KonradStaniec) [inline finality-provider/service/chain_poller.go:265]: I would argue this is not correct fix due two things.

1. From api perspective, I would be suprised if I set some height and component would just ignore it

2. Looking at:
```
			cp.SetNextHeight(blockToRetrieve + 1)
			failedCycles = 0
			cp.logger.Info("the poller retrieved the block from the consumer chain",
				zap.Uint64("height", block.Height))
			// push the data to the channel
			// Note: if the consumer is too slow -- the buffer is full
			// the channel will block, and we will stop retrieving data from the node
			cp.blockInfoChan <- block
```
In scenario in which update happen mid download, old block is still pushed onto the channel. This is imo unexpected from the pov of the caller.

Comment (KonradStaniec) [reply finality-provider/service/chain_poller.go:265]: hmm thats one option, although sharing channels is tricky to get right and couples components.

Another option would be to have some thing like:
```
type restartRequest struct {
	height uint64
	resp   chan struct{}
}
```

and in poller:
```
restartChan chan *restartRequest
```

then you can add another case to selec in poller:
```
		select {
		case req := <-cp.restartChan:
			// drain blockInfoChan channel
			// sent next height to req.height
			req.resp <- struct{}{}

```
and have proper restart from heigh function:
```
func (cp *ChainPoller) RestartFromHeight(height uint64) {
	resp := make(chan struct{}, 1)
	cp.restartChan <- &restartRequest{height: height, resp: resp}
	<-resp
}
```

Now after restart is called, buffer will always return block higher or equal `height`. Also you can restart poller from any height.

One downside is that if we are mid `blockWithRetry` request it will wait for it to finish. This could be improved by storing `cancelFunc` in chain poller if there is request happening, but it is debatable whether this is necessary.

Comment (gitferry) [reply finality-provider/service/chain_poller.go:265]: Looks great. Thanks! Will implement

**Comment by gitferry** [comment]
@KonradStaniec Thanks for your valuable comments. I have made changes accordingly and added unit tests. Please review it again. Thanks!

File: finality-provider/service/chain_poller.go [hunk 3]
```diff
@@ -46,11 +55,12 @@ func NewChainPoller(
...
-		logger:        logger,
-		cfg:           cfg,
-		cc:            cc,
-		blockInfoChan: make(chan *types.BlockInfo, cfg.BufferSize),
-		quit:          make(chan struct{}),
+		logger:         logger,
+		cfg:            cfg,
+		cc:             cc,
+		blockInfoChan:  make(chan *types.BlockInfo, cfg.BufferSize),
+		skipHeightChan: make(chan *skipHeightRequest, 1),
```
Comment (KonradStaniec) [inline finality-provider/service/chain_poller.go:62]: this probably can be unbuffered, so that skip by height request do not accumulate

File: finality-provider/service/chain_poller.go [hunk 4]
```diff
@@ -242,37 +252,47 @@ func (cp *ChainPoller) pollChain() {
...
+
 		case <-cp.quit:
 			return
 		}
 	}
 }
 
-func (cp *ChainPoller) GetNextHeight() uint64 {
-	return cp.getNextHeight()
+func (cp *ChainPoller) SkipToHeight(height uint64) error {
```
Comment (KonradStaniec) [inline finality-provider/service/chain_poller.go:285]: this needs to cover two additional cases:
1.  some one closed poller before calling `SkipToHeight`. If that happened then request will never be processed and this will hang
2. some one closed poller while waiting for response to `&skipHeightRequest`

This can be acheived by writing this function like:
```
func (cp *ChainPoller) SkipToHeight(height uint64) error {
	respChan := make(chan *skipHeightResponse, 1)

	select {
	case <-cp.quit:
		return fmt.Errorf("the chain poller is stopped")
	case cp.skipHeightChan <- &skipHeightRequest{height: height, resp: respChan}:
	}

	select {
	case <-cp.quit:
		return fmt.Errorf("the chain poller is stopped")
	case resp := <-respChan:
		return resp.err
	}
}
```
This is a bit mouthful so in oder repos we have some utils to do this like in staker - https://github.com/babylonchain/btc-staker/blob/main/utils/utils.go#L37

**Review by KonradStaniec — COMMENTED** [review]
thanks for changes (and tests 👍 )

just two small additional comments

File: finality-provider/service/chain_poller.go (hunk 4 above)
Comment (gitferry) [reply finality-provider/service/chain_poller.go:295]: Nice find! I also realized that we should return error if the poller has not been started yet. To cover these cases, I changed `startOnce/stopOnce sync.Once` to `isStarted *atomic.Bool` and added your suggestions above. Also, I have changed the tests to cover these cases. Please take a look again. Thanks!
